/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JFileChooser;

/**
 *
 * @author lucas
 */
public class CompilerView extends javax.swing.JFrame {
    private String fileName;
    private String code;
    /**
     * Creates new form NewJFrame
     */
    public CompilerView() {
        initComponents();
        
        EditorJTextArea.setBorder(new NumberedBorder());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        jPanel3 = new javax.swing.JPanel();
        javax.swing.JPanel ToolbarJPanel = new javax.swing.JPanel();
        NewJButton = new javax.swing.JButton();
        OpenJButton = new javax.swing.JButton();
        SaveJButton = new javax.swing.JButton();
        TeamJButton = new javax.swing.JButton();
        CopyJButton = new javax.swing.JButton();
        CutJButton = new javax.swing.JButton();
        PasteJButton = new javax.swing.JButton();
        CompileJButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        StatusJLabel = new javax.swing.JLabel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        EditorJTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        OutputJTextArea = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1500, 800));
        setMinimumSize(new java.awt.Dimension(1500, 800));
        setPreferredSize(new java.awt.Dimension(1500, 800));

        ToolbarJPanel.setBackground(new java.awt.Color(204, 204, 204));
        ToolbarJPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NewJButton.setText("Novo [ctrl+n]");
        NewJButton.setToolTipText("");

        OpenJButton.setText("Abrir [ctrl+o]");
        OpenJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpenJButtonMouseClicked(evt);
            }
        });

        SaveJButton.setText("Salvar [ctrl+s]");
        SaveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveJButtonActionPerformed(evt);
            }
        });

        TeamJButton.setText("Equipe");
        TeamJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TeamJButtonMouseClicked(evt);
            }
        });
        TeamJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamJButtonActionPerformed(evt);
            }
        });

        CopyJButton.setText("Copiar [ctrl+c]");
        CopyJButton.setToolTipText("");
        CopyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyJButtonActionPerformed(evt);
            }
        });

        CutJButton.setText("Recortar [ctrl+x]");
        CutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CutJButtonActionPerformed(evt);
            }
        });

        PasteJButton.setText("Colar [ctrl+v]");
        PasteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasteJButtonActionPerformed(evt);
            }
        });

        CompileJButton.setText("Compilar [F7]");
        CompileJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompileJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ToolbarJPanelLayout = new javax.swing.GroupLayout(ToolbarJPanel);
        ToolbarJPanel.setLayout(ToolbarJPanelLayout);
        ToolbarJPanelLayout.setHorizontalGroup(
            ToolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolbarJPanelLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(OpenJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SaveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(479, 479, 479)
                .addComponent(TeamJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1758, Short.MAX_VALUE))
            .addGroup(ToolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ToolbarJPanelLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(NewJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1378, Short.MAX_VALUE)))
            .addGroup(ToolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ToolbarJPanelLayout.createSequentialGroup()
                    .addGap(345, 345, 345)
                    .addComponent(CopyJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1049, Short.MAX_VALUE)))
            .addGroup(ToolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ToolbarJPanelLayout.createSequentialGroup()
                    .addGap(461, 461, 461)
                    .addComponent(CutJButton)
                    .addContainerGap(923, Short.MAX_VALUE)))
            .addGroup(ToolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ToolbarJPanelLayout.createSequentialGroup()
                    .addGap(577, 577, 577)
                    .addComponent(PasteJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(817, Short.MAX_VALUE)))
            .addGroup(ToolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ToolbarJPanelLayout.createSequentialGroup()
                    .addGap(699, 699, 699)
                    .addComponent(CompileJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(695, Short.MAX_VALUE)))
        );
        ToolbarJPanelLayout.setVerticalGroup(
            ToolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolbarJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ToolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OpenJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(SaveJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(TeamJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(ToolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ToolbarJPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(NewJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(ToolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ToolbarJPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(CopyJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(ToolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ToolbarJPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(CutJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(ToolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ToolbarJPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PasteJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(ToolbarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ToolbarJPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(CompileJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StatusJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1803, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StatusJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jSplitPane2.setDividerLocation(500);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        EditorJTextArea.setColumns(20);
        EditorJTextArea.setRows(5);
        jScrollPane2.setViewportView(EditorJTextArea);

        jSplitPane2.setTopComponent(jScrollPane2);

        OutputJTextArea.setEditable(false);
        OutputJTextArea.setColumns(20);
        OutputJTextArea.setRows(5);
        jScrollPane4.setViewportView(OutputJTextArea);

        jSplitPane2.setRightComponent(jScrollPane4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ToolbarJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSplitPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ToolbarJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SaveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveJButtonActionPerformed

    private void TeamJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeamJButtonActionPerformed

    private void CopyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CopyJButtonActionPerformed

    private void CutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CutJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CutJButtonActionPerformed

    private void PasteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasteJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasteJButtonActionPerformed

    private void CompileJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompileJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompileJButtonActionPerformed

    private void TeamJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeamJButtonMouseClicked
        ClearOutput();
        LogOutput("Lucas Lewin Vilbert");
    }//GEN-LAST:event_TeamJButtonMouseClicked

    private void OpenJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenJButtonMouseClicked
        var option = jFileChooser.showOpenDialog(jPanel3);
        if(option == JFileChooser.APPROVE_OPTION){
            StatusJLabel.setText(jFileChooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_OpenJButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompilerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompilerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompilerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompilerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompilerView().setVisible(true);
            }
        });
    }

    private void ClearOutput(){
        
        
        OutputJTextArea.setText("");
    }
    
    private void LogOutput(String msg){
        var text = OutputJTextArea.getText();
        text+="\n"+msg;
        OutputJTextArea.setText(text);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CompileJButton;
    private javax.swing.JButton CopyJButton;
    private javax.swing.JButton CutJButton;
    private javax.swing.JTextArea EditorJTextArea;
    private javax.swing.JButton NewJButton;
    private javax.swing.JButton OpenJButton;
    private javax.swing.JTextArea OutputJTextArea;
    private javax.swing.JButton PasteJButton;
    private javax.swing.JButton SaveJButton;
    private javax.swing.JLabel StatusJLabel;
    private javax.swing.JButton TeamJButton;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane2;
    // End of variables declaration//GEN-END:variables
}
